app = "ownerpay-staging"
primary_region = "iad"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/healthz"

[env]
  SENTRY_DSN = ""
  MEMO_CDN_BASE = "https://cdn-staging.ownerpay.dev"
  RATE_LIMIT_REDIS_URL = ""

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"


